services:
  db:
    image: mysql:8.4.3
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mocks:
    image: matheusprotzen/gateways-mock
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  db_data:
  mocks: